# Generated by Django 4.2.7 on 2025-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0002_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=50)),
                ('starting_price', models.IntegerField(default=0)),
                ('reserve_price', models.IntegerField(default=0)),
                ('quantity', models.PositiveIntegerField()),
                ('auction_duration', models.IntegerField()),
                ('listing_time', models.TimeField()),
                ('certified', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('origin', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_principal', models.BooleanField(default=False)),
            ],
        ),
    ]
