# Generated by Django 4.2.7 on 2025-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_time',
            field=models.TimeField(null=True),
        ),
    ]
