# Generated by Django 4.2.7 on 2025-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0004_alter_product_listing_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
