# Generated by Django 4.2.7 on 2025-02-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0005_rename_product_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_principal',
            new_name='is_approved',
        ),
    ]
