# Generated by Django 4.2.7 on 2025-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0006_rename_is_principal_products_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='listing_time',
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.TimeField(null=True),
        ),
    ]
