# Generated by Django 4.2.7 on 2025-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0007_remove_products_listing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bid_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
