# Generated by Django 4.2.7 on 2025-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0011_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
