# Generated by Django 4.2.7 on 2025-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0012_products_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
