# Generated by Django 4.2.7 on 2025-02-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0014_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='product_name',
        ),
    ]
