# Generated by Django 4.2.7 on 2025-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0015_remove_bids_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='spice_video',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
