# Generated by Django 4.2.7 on 2025-02-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0016_products_spice_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='spice_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
