# Generated by Django 4.2.7 on 2025-02-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0017_alter_products_spice_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
