# Generated by Django 4.2.7 on 2025-02-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0018_products_created_alter_products_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='created_at',
            new_name='timeleft',
        ),
    ]
