# Generated by Django 4.2.7 on 2025-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0019_rename_created_at_products_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='timeleft',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
