# Generated by Django 4.2.7 on 2025-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0020_alter_products_timeleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='timeleft',
        ),
    ]
