# Generated by Django 4.2.7 on 2025-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0021_remove_products_timeleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
