# Generated by Django 4.2.7 on 2025-02-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0022_products_is_ended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='descripton',
            new_name='description',
        ),
    ]
