# Generated by Django 4.2.7 on 2025-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0023_rename_descripton_notification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
