# Generated by Django 4.2.7 on 2025-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0024_products_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='balance',
            field=models.FloatField(default=10000),
        ),
    ]
