# Generated by Django 4.2.7 on 2025-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0025_alter_products_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=10000),
        ),
    ]
