# Generated by Django 4.2.7 on 2025-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceapp', '0026_remove_products_balance_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
